name: Yourator Job Crawler

on:
  schedule:
    - cron: "0 0 */1 * *" # run every day
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Yourator crawler
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_YOURATOR_CHANNEL_ID: ${{ secrets.DISCORD_YOURATOR_CHANNEL_ID }}
        run: python yourator_crawler.py
